services:
  ecommerce-order-db:
    image: mongo:latest
    container_name: ecommerce-order-db
    networks:
      - microservice-application-app-networks
    ports:
      - "4988:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 8682a9191fb618ce452cacdd0a1246370cf9ce7a0b4515a8f2a094e2ed839d00
    volumes:
      - ./mongo-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb:/data/db
  ecommerce-db-auth:
    image: postgres:16.2-alpine3.19
    container_name: ecommerce-db-auth
    ports:
      - "4848:5432"
    environment:
      POSTGRES_USER: "ecommercedbauth"
      POSTGRES_PASSWORD: "52e91258b667c2b01de5"
      POSTGRES_DB: "ecommercedbauth"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - pg-database:/var/lib/postgresql/data
    networks:
      - microservice-application-app-networks
  ecommerce-db-product:
    image: mysql:latest
    container_name: ecommerce-db-product
    ports:
      - "4849:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "ec31d315916485460cadb7fc58c90118795ddeccb75147e5d38d4dbcde433c1c"
      MYSQL_DATABASE: "ecommercedbproduct"
      MYSQL_PASSWORD: "901a923055b3341e6effff67a8e133391c66aa2921dbedf1b834de0f583ec85b"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - mysql-database:/var/lib/mysql
    networks:
      - microservice-application-app-networks
  ecommerce-users-api-service:
    image: pzwitthawasdev/ecommerce-users-api-service:latest
    container_name: ecommerce-users-api-service
    ports:
      - "4000:8080"
    environment:
      ConnectionStrings__PostgresSQLConnection: "Host=ecommerce-db-auth;Port=5432;Database=ecommercedbauth;Username=ecommercedbauth;Password=52e91258b667c2b01de5"
    depends_on:
      - ecommerce-db-auth
    networks:
      - microservice-application-app-networks
  ecommerce-product-api-service:
    image: pzwitthawasdev/ecommerce-products-api-service:latest
    container_name: ecommerce-product-api-service
    ports:
      - "4001:8080"
    environment:
      ConnectionStrings__MySqlConnection: "server=ecommerce-db-product;port=3306;database=ecommercedbproduct;user=root;password=ec31d315916485460cadb7fc58c90118795ddeccb75147e5d38d4dbcde433c1c"
    depends_on:
      - ecommerce-db-product
    networks:
      - microservice-application-app-networks
  ecommerce-orders-api-service:
    image: pzwitthawasdev/ecommerce-orders-api-service:latest
    container_name: ecommerce-orders-api-service
    ports:
      - "4002:8080"
    environment:
        MONGO_USER: "root"
        MONGO_PASSWORD: "8682a9191fb618ce452cacdd0a1246370cf9ce7a0b4515a8f2a094e2ed839d00"
        MONGO_HOST: "ecommerce-order-db"
        MONGO_PORT: "27017"
        ConnectionStrings__MongoDbConnection: "mongodb://{MONGO_USER}:{MONGO_PASSWORD}@{MONGO_HOST}:{MONGO_PORT}"
    depends_on:
      - ecommerce-order-db
    networks:
      - microservice-application-app-networks
networks:
  microservice-application-app-networks:
    driver: bridge
volumes:
  pg-database:
    driver: local
  mysql-database:
    driver: local
  mongodb:
    driver: local
