apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-depl
  namespace: ecommerce-namespace
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: ecomwwpzpremregistry.azurecr.io/apigetway:latest
          ports:
            - containerPort: 8080