apiVersion: v1
kind: Service
metadata:
  name: ecommerce-orders-api-service
  namespace: ecommerce-namespace
spec:
  selector:
    app: order-microservice-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
