apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-depl
  namespace: ecommerce-namespace
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4.0.5-management-alpine
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "8bf0f3bde1588cd2fca6a7c35e932173"
          ports:
            - containerPort: 5672
            - containerPort: 15672
